version: '3.8'

services:
  serveur:
    build:
      context: ./serveur
      dockerfile: Dockerfile
    image: iris-serveur:latest
    ports:
      - "8000:8000"
    volumes:
      - ./serveur:/app
      - ./serveur/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      - iris-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: iris-client:latest
    ports:
      - "8501:8501"
    volumes:
      - ./client:/app
    depends_on:
      serveur:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://serveur:8000
    networks:
      - iris-network

  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    image: iris-tensorboard:latest
    ports:
      - "6006:6006"
    volumes:
      - ./artifacts/tensorboard:/tensorboard_logs
    command: ["--logdir=/tensorboard_logs", "--host=0.0.0.0", "--port=6006", "--reload_interval=5"]
    networks:
      - iris-network

networks:
  iris-network:
    driver: bridge