version: '3.8'

services:
  backend:
    build: 
      context: ./serveur
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./serveur:/app
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    volumes:
      - ./client:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge