version: "3.8"

services:
  backend:
    build:
      context: .                # on build depuis la racine (où il y a serveur/ et models/)
      dockerfile: serveur/Dockerfile
    container_name: iris-backend
    ports:
      - "8000:80"               # host:container (FastAPI expose 80 dans le conteneur)
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app

  frontend:
    build:
      context: ./client         # front dans le dossier client
      dockerfile: Dockerfile
    container_name: iris-frontend
    ports:
      - "8502:8501"             # http://localhost:8502
    environment:
      - BACKEND_URL=http://backend:80   # variable cohérente avec ton app.py
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge
