version: '3.8'

services:
  serveur:
    build:
      context: ./serveur
      dockerfile: Dockerfile
    image: iris-serveur:latest
    ports:
      - "8000:8000"
    volumes:
      - ./serveur:/app
      - ./serveur/models:/app/models
      - ./serveur/logs/tensorboard:/app/logs/tensorboard  # Ajout du volume pour TensorBoard
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      iris-network:
        aliases:
          - backend

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: iris-client:latest
    ports:
      - "8501:8501"
    volumes:
      - ./client:/app
    depends_on:
      - serveur
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://backend:8000
    networks:
      - iris-network

  tensorboard:
    image: tensorflow/tensorflow:latest
    ports:
      - "6006:6006"
    volumes:
      - ./serveur/logs/tensorboard:/tensorboard_logs:ro
    command: tensorboard --logdir=/tensorboard_logs --host=0.0.0.0 --port=6006 --reload_interval=5 --bind_all
    networks:
      - iris-network
    depends_on:
      - serveur

networks:
  iris-network:
    driver: bridge