version: '3.8'

services:
  serveur:
    build:
      context: ./serveur
      dockerfile: Dockerfile
    image: iris-serveur:latest
    ports:
      - "8000:8000"
    volumes:
      - ./serveur:/app
      - ./serveur/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    networks:
      iris-network:
        aliases:
          - backend  # AJOUTEZ CETTE LIGNE

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: iris-client:latest
    ports:
      - "8501:8501"
    volumes:
      - ./client:/app
    depends_on:
      - serveur
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://backend:8000  # Maintenant "backend" fonctionnera
    networks:
      - iris-network

  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    image: iris-tensorboard:latest
    ports:
      - "6007:6006"
    volumes:
      - ./artifacts/tensorboard:/tensorboard_logs
    command: tensorboard --logdir=/tensorboard_logs --host=0.0.0.0 --port=6006 --reload_interval=5
    networks:
      - iris-network

networks:
  iris-network:
    driver: bridge