version: "3.8"

services:
  backend:
    build:
      context: ./serveur
      dockerfile: Dockerfile        # écoute 80 dans le conteneur
    ports:
      - "8000:80"                   # host:container
    environment:
      - PYTHONUNBUFFERED=1
    networks: [app]

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile        # écoute 8501 dans le conteneur
    ports:
      - "8502:8501"                 # http://localhost:8502
    environment:
      - API_URL=http://backend:80   # appel API via le réseau Docker
    depends_on:
      - backend
    networks: [app]

networks:
  app:
    driver: bridge
